services:
  accounts:
    image: "shyamsundhar2435/accounts:s4"
    container_name: accounts-microservice
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
    loans:
      image: "shyamsundhar2435/loans:s4"
      container_name: loans-microservice
      ports:
        - "8090:8090"
      deploy:
        resources:
          limits:
            memory: 700m
      networks:
        - bank
    cards:
      image: "shyamsundhar2435/cards:s4"
      container_name: cards-microservice
      ports:
        - "9000:9000"
      deploy:
        resources:
          limits:
            memory: 700m
      networks:
        - bank
networks:
  bank:
    driver: "bridge"
