services:
  configserver:
    image: "shyamsundhar2435/configserver:s6"
    container_name: configserver-microservice
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl -f -s localhost:8071/actuator/health/readiness| grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "shyamsundhar2435/accounts:s6"
    container_name: accounts-microservice
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-configserver-config


  loans:
    image: "shyamsundhar2435/loans:s6"
    container_name: loans-microservice
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy

    environment:
      SPRING_APPLICATION_NAME: "loans"

    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "shyamsundhar2435/cards:s6"
    container_name: cards-microservice
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_healthy

    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  bank:
    driver: "bridge"